# Generated by Django 2.2.14 on 2021-04-20 04:38

from django.db import migrations, models
import ecomapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_auto_20210419_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=ecomapp.models.upload_file_path),
        ),
    ]
