# Generated by Django 2.2.14 on 2021-05-05 11:22

from django.db import migrations, models
import ecomapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderId',
            field=models.CharField(blank=True, default=ecomapp.models.Order.increment_order_number, max_length=500, null=True),
        ),
    ]
