# Generated by Django 2.2.14 on 2021-05-07 05:03

from django.db import migrations, models
import ecomapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_auto_20210506_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='phoneNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.CharField(blank=True, default='Ordered Confirmed', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNo',
            field=models.CharField(blank=True, default=ecomapp.models.Order.increment_order_number, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='ordered',
            field=models.CharField(blank=True, default='active', max_length=100, null=True),
        ),
    ]
