# Generated by Django 2.2.14 on 2021-04-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20210407_1336'),
        ('auth', '0011_update_proxy_permissions'),
        ('ecomapp', '0008_auto_20210407_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User1',
            new_name='User',
        ),
    ]
